## NumPy stands for Numerical Python.

### NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

### Numpy arrays are 50-100x faster the simple python list

In [144]:
!pip install numpy

In [145]:
import numpy as np

In [146]:
np.__version__

'1.24.3'

In [148]:
arr1 = np.array([1, 2, 3, 4, 5]) 

print(arr1)

[1 2 3 4 5]


In [167]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # np.array([[1,2,3], [4,5,6]])

print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [150]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10,11, 12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [151]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


## Array Indexing

### 1D Array

In [9]:
arr1

array([1, 2, 3, 4, 5])

In [154]:
arr1[0]

1

In [11]:
arr1[3]

4

In [155]:
arr1[4] 

5

In [159]:
arr1[-5]

1

### 2D Array

In [168]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [171]:
arr2[1,2]  # arr2[row, col]

8

In [16]:
arr2[0,2]

3

In [17]:
arr2[1,1]

5

In [172]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [178]:
print(arr3[1, 1, 1])

11


 ### Array Slicing

In [180]:
print(arr1)

[1 2 3 4 5]


In [187]:
print(arr1[:3]) # arr1[start: end]  end = end-1

[1 2 3]


In [24]:
print(arr1[2:])

[3 4 5]


In [25]:
print(arr[:3])

[1 2 3]


In [27]:
print(arr1[-1])

5


In [29]:
print(arr1[-3:-1])

[3 4]


In [31]:
print(arr1[1:5:2])

[2 4]


In [32]:
print(arr1[::2])

[1 3 5]


In [188]:
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [190]:
print(arr2[1,0:3])

[6 7 8]


In [49]:
print(arr2[0:2, 2])

[3 8]


In [52]:
print(arr2[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### Data Types in Numpy

In [191]:
arr4 = np.array([1, 2, 3, 4])

arr4.dtype

dtype('int32')

In [192]:
arr5 = np.array(['apple', 'banana', 'cherry'])

arr5.dtype

dtype('<U6')

In [194]:
arr6 = np.array([1.1, 2.1, 3.1])
print(arr6)

[1.1 2.1 3.1]


In [197]:
arr6.dtype

dtype('float64')

In [199]:
arr6 = arr6.astype('i') # function arrayname.astype('i')
print(arr6)

[1 2 3]


In [202]:
arr7 = np.array([1.1, 2.1, 3.1], dtype='i')
print(arr7)

[1 2 3]


In [75]:
arr7.dtype

dtype('int32')

### Maths and Stats

In [205]:
# Generate a random integer from 0 to 100
x = np.random.randint(100)

print(x)

90


In [208]:
# Generate a random float from 0 to 1
y = np.random.rand()

print(y)

0.49054068439328213


In [211]:
arr8=np.random.randint(1000, size=(5))

print(arr8)

[511 447 964 245 208]


In [213]:
arr9 = np.random.randint(100, size=(3, 5))

print(arr9)

[[38 70 58 47 98]
 [64 42 42 23 78]
 [65 63 90 93 99]]


In [214]:
arr10 = np.random.rand(5)

print(arr10)

[0.57649378 0.22824087 0.59990051 0.62145336 0.43245287]


In [215]:
arr11 = random.rand(3, 5)

print(arr11)

[[0.77339838 0.51889013 0.18472595 0.10186288 0.78634909]
 [0.70802365 0.83266919 0.6026774  0.84143999 0.01343227]
 [0.3199974  0.41788183 0.10676745 0.06229594 0.92756312]]


In [218]:
arr12 = np.random.choice([3, 5, 7, 9])

print(arr12)

3


In [219]:
arr13 = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(arr13)

[[7 3 3 9 3]
 [5 9 5 3 9]
 [7 7 3 7 9]]


### Arthimetic functions

In [98]:
arr14 = np.array([10, 11, 12, 13, 14, 15])
arr15= np.array([20, 21, 22, 23, 24, 25])

In [220]:
addarr = np.add(arr14, arr15)

print(addarr)

[30 32 34 36 38 40]


In [221]:
subarr = np.subtract(arr14, arr15)

print(subarr)

[-10 -10 -10 -10 -10 -10]


In [222]:
mularr = np.multiply(arr14, arr15)

print(mularr)

[200 231 264 299 336 375]


In [223]:
arr16 = np.array([10, 20, 30, 40, 50, 60])
arr17 = np.array([3, 5, 10, 8, 2, 33])
divarr = np.divide(arr16, arr17)

print(divarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [106]:
powarr = np.power(arr16, arr17)

print(powarr)

[      1000    3200000  716276736 -520093696       2500          0]


In [224]:
modarr = np.mod(arr16, arr17)

print(modarr)

[ 1  0  0  0  0 27]


In [225]:
arr18 = np.floor([3.1666, 3.6667])

print(arr18)

[3. 3.]


In [115]:
arr19 = np.ceil([3.1666, 3.6667])

print(arr19)

[4. 4.]


### Stats Function

In [228]:
arr20 = np.array([1, 2, 3])
arr21 = np.array([1, 2, 3])

newarr = np.sum([arr20, arr21], axis=0)

print(newarr)

[2 4 6]


In [229]:
arr22 = np.array([1, 2, 4, 5, 6])
mean = np.mean(arr22)
print(mean)

3.6


In [230]:
median = np.median(arr22)
print(median)

4.0


In [231]:
min_num = np.min(arr22)
print(min_num)

1


In [232]:
max_num = np.max(arr22)
print(max_num)

6


In [143]:
std_deviation = np.std(arr22)
print(std_deviation)

1.8547236990991407
